"""add_preprocessed_image_path_to_document_pages

Revision ID: b61940e9e225
Revises: b2491e5a4876
Create Date: 2025-11-16 08:58:00.622420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61940e9e225'
down_revision: Union[str, None] = 'b2491e5a4876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_pages', sa.Column('preprocessed_image_path', sa.Text(), nullable=True))
    op.drop_index('idx_extraction_jobs_tenant_id', table_name='extraction_jobs')
    op.drop_constraint('extraction_jobs_tenant_id_fkey', 'extraction_jobs', type_='foreignkey')
    op.drop_column('extraction_jobs', 'tenant_id')
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=False)
    op.create_index(op.f('ix_workflow_executions_conductor_workflow_id'), 'workflow_executions', ['conductor_workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_tenant_id'), 'workflow_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_version_id'), 'workflow_executions', ['workflow_version_id'], unique=False)
    op.create_index(op.f('ix_workflow_node_executions_status'), 'workflow_node_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_node_executions_workflow_execution_id'), 'workflow_node_executions', ['workflow_execution_id'], unique=False)
    op.drop_index('idx_workflow_versions_conductor_name', table_name='workflow_versions')
    op.create_index(op.f('ix_workflow_versions_conductor_workflow_name'), 'workflow_versions', ['conductor_workflow_name'], unique=False)
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_conductor_workflow_name'), table_name='workflow_versions')
    op.create_index('idx_workflow_versions_conductor_name', 'workflow_versions', ['conductor_workflow_name'], unique=False)
    op.drop_index(op.f('ix_workflow_node_executions_workflow_execution_id'), table_name='workflow_node_executions')
    op.drop_index(op.f('ix_workflow_node_executions_status'), table_name='workflow_node_executions')
    op.drop_index(op.f('ix_workflow_executions_workflow_version_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_tenant_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_conductor_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.add_column('extraction_jobs', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('extraction_jobs_tenant_id_fkey', 'extraction_jobs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_extraction_jobs_tenant_id', 'extraction_jobs', ['tenant_id'], unique=False)
    op.drop_column('document_pages', 'preprocessed_image_path')
    # ### end Alembic commands ###
