"""Add processing_mode to extraction_jobs

Revision ID: 230e72f5ab37
Revises: 7486d8a3f67d
Create Date: 2025-11-02 17:34:21.596276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '230e72f5ab37'
down_revision: Union[str, None] = '7486d8a3f67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_document_pages_document_id', table_name='document_pages')
    op.drop_index('ix_document_pages_status', table_name='document_pages')
    op.create_index('idx_document_pages_document_id', 'document_pages', ['document_id'], unique=False)
    op.create_index('idx_document_pages_unique', 'document_pages', ['document_id', 'page_number'], unique=True)
    op.drop_column('document_pages', 'updated_at')
    op.alter_column('documents', 'size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    # Add column as nullable first, set default for existing rows, then make it NOT NULL
    op.add_column('extraction_jobs', sa.Column('processing_mode', sa.String(length=50), nullable=True))
    op.execute("UPDATE extraction_jobs SET processing_mode = 'per_page' WHERE processing_mode IS NULL")
    op.alter_column('extraction_jobs', 'processing_mode', nullable=False)
    op.alter_column('extraction_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('extraction_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('extraction_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_extraction_jobs_celery_task_id', table_name='extraction_jobs')
    op.drop_index('ix_extraction_jobs_created_at', table_name='extraction_jobs')
    op.drop_index('ix_extraction_jobs_document_id', table_name='extraction_jobs')
    op.drop_index('ix_extraction_jobs_status', table_name='extraction_jobs')
    op.create_index('idx_extraction_jobs_celery_task_id', 'extraction_jobs', ['celery_task_id'], unique=False)
    op.create_index('idx_extraction_jobs_document_id', 'extraction_jobs', ['document_id'], unique=False)
    op.create_index('idx_extraction_jobs_status', 'extraction_jobs', ['status'], unique=False)
    op.alter_column('extraction_results', 'document_page_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('extraction_results', 'model_used',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('extraction_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_extraction_results_document_page_id', table_name='extraction_results')
    op.drop_index('ix_extraction_results_extraction_job_id', table_name='extraction_results')
    op.create_index('idx_extraction_results_extracted_data', 'extraction_results', ['extracted_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_extraction_results_job_id', 'extraction_results', ['extraction_job_id'], unique=False)
    op.create_index('idx_extraction_results_unique', 'extraction_results', ['extraction_job_id', 'document_page_id'], unique=True)
    op.drop_column('extraction_results', 'validation_errors')
    op.add_column('model_provider_keys', sa.Column('provider', sa.String(length=50), nullable=False))
    op.alter_column('model_provider_keys', 'api_key_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('model_provider_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_model_provider_keys_is_active', table_name='model_provider_keys')
    op.drop_index('ix_model_provider_keys_provider_name', table_name='model_provider_keys')
    op.create_index('idx_model_provider_keys_provider', 'model_provider_keys', ['provider'], unique=True)
    op.create_unique_constraint(None, 'model_provider_keys', ['provider'])
    op.drop_column('model_provider_keys', 'provider_name')
    op.drop_column('model_provider_keys', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_provider_keys', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('model_provider_keys', sa.Column('provider_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_provider_keys', type_='unique')
    op.drop_index('idx_model_provider_keys_provider', table_name='model_provider_keys')
    op.create_index('ix_model_provider_keys_provider_name', 'model_provider_keys', ['provider_name'], unique=False)
    op.create_index('ix_model_provider_keys_is_active', 'model_provider_keys', ['is_active'], unique=False)
    op.alter_column('model_provider_keys', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_provider_keys', 'api_key_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('model_provider_keys', 'provider')
    op.add_column('extraction_results', sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('idx_extraction_results_unique', table_name='extraction_results')
    op.drop_index('idx_extraction_results_job_id', table_name='extraction_results')
    op.drop_index('idx_extraction_results_extracted_data', table_name='extraction_results', postgresql_using='gin')
    op.create_index('ix_extraction_results_extraction_job_id', 'extraction_results', ['extraction_job_id'], unique=False)
    op.create_index('ix_extraction_results_document_page_id', 'extraction_results', ['document_page_id'], unique=False)
    op.alter_column('extraction_results', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_results', 'model_used',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('extraction_results', 'document_page_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_extraction_jobs_status', table_name='extraction_jobs')
    op.drop_index('idx_extraction_jobs_document_id', table_name='extraction_jobs')
    op.drop_index('idx_extraction_jobs_celery_task_id', table_name='extraction_jobs')
    op.create_index('ix_extraction_jobs_status', 'extraction_jobs', ['status'], unique=False)
    op.create_index('ix_extraction_jobs_document_id', 'extraction_jobs', ['document_id'], unique=False)
    op.create_index('ix_extraction_jobs_created_at', 'extraction_jobs', ['created_at'], unique=False)
    op.create_index('ix_extraction_jobs_celery_task_id', 'extraction_jobs', ['celery_task_id'], unique=False)
    op.alter_column('extraction_jobs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_jobs', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('extraction_jobs', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('extraction_jobs', 'processing_mode')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('document_pages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('idx_document_pages_unique', table_name='document_pages')
    op.drop_index('idx_document_pages_document_id', table_name='document_pages')
    op.create_index('ix_document_pages_status', 'document_pages', ['status'], unique=False)
    op.create_index('ix_document_pages_document_id', 'document_pages', ['document_id'], unique=False)
    op.alter_column('document_pages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
