"""add_multi_tenancy_and_auth

Revision ID: 92e8a3aa9513
Revises: 085e0bd93771
Create Date: 2025-11-02 23:29:20.977863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92e8a3aa9513'
down_revision: Union[str, None] = '085e0bd93771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_packages_is_active', 'credit_packages', ['is_active'], unique=False)
    op.create_index('idx_credit_packages_sort_order', 'credit_packages', ['sort_order'], unique=False)
    op.create_index(op.f('ix_credit_packages_stripe_price_id'), 'credit_packages', ['stripe_price_id'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_permissions_action', 'permissions', ['action'], unique=False)
    op.create_index('idx_permissions_name', 'permissions', ['name'], unique=False)
    op.create_index('idx_permissions_resource', 'permissions', ['resource'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('credit_unit_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tenant_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenants_created_at', 'tenants', ['created_at'], unique=False)
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_transactions_created_at', 'credit_transactions', ['created_at'], unique=False)
    op.create_index('idx_credit_transactions_tenant_id', 'credit_transactions', ['tenant_id'], unique=False)
    op.create_index('idx_credit_transactions_type', 'credit_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_credit_transactions_stripe_payment_intent_id'), 'credit_transactions', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_tenant_id'), 'credit_transactions', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roles_is_system', 'roles', ['is_system'], unique=False)
    op.create_index('idx_roles_name', 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('idx_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_permissions_permission_id', 'user_permissions', ['permission_id'], unique=False)
    op.create_index('idx_user_permissions_unique', 'user_permissions', ['user_id', 'permission_id'], unique=True)
    op.create_index('idx_user_permissions_user_id', 'user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_permission_id'), 'user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index('idx_documents_tenant_id', 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('schema_definitions', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.drop_constraint('schema_definitions_name_key', 'schema_definitions', type_='unique')
    op.drop_index('idx_schema_definitions_name', table_name='schema_definitions')
    op.create_index('idx_schema_definitions_name', 'schema_definitions', ['tenant_id', 'name'], unique=True)
    op.create_index('idx_schema_definitions_tenant_id', 'schema_definitions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_schema_definitions_tenant_id'), 'schema_definitions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'schema_definitions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schema_definitions', type_='foreignkey')
    op.drop_index(op.f('ix_schema_definitions_tenant_id'), table_name='schema_definitions')
    op.drop_index('idx_schema_definitions_tenant_id', table_name='schema_definitions')
    op.drop_index('idx_schema_definitions_name', table_name='schema_definitions')
    op.create_index('idx_schema_definitions_name', 'schema_definitions', ['name'], unique=False)
    op.create_unique_constraint('schema_definitions_name_key', 'schema_definitions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('schema_definitions', 'tenant_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index('idx_documents_tenant_id', table_name='documents')
    op.drop_column('documents', 'tenant_id')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_permission_id'), table_name='user_permissions')
    op.drop_index('idx_user_permissions_user_id', table_name='user_permissions')
    op.drop_index('idx_user_permissions_unique', table_name='user_permissions')
    op.drop_index('idx_user_permissions_permission_id', table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_role_permissions_role_id', table_name='role_permissions')
    op.drop_index('idx_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_tenant_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index('idx_roles_name', table_name='roles')
    op.drop_index('idx_roles_is_system', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_credit_transactions_tenant_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_stripe_payment_intent_id'), table_name='credit_transactions')
    op.drop_index('idx_credit_transactions_type', table_name='credit_transactions')
    op.drop_index('idx_credit_transactions_tenant_id', table_name='credit_transactions')
    op.drop_index('idx_credit_transactions_created_at', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_index('idx_tenants_created_at', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index('idx_permissions_resource', table_name='permissions')
    op.drop_index('idx_permissions_name', table_name='permissions')
    op.drop_index('idx_permissions_action', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_credit_packages_stripe_price_id'), table_name='credit_packages')
    op.drop_index('idx_credit_packages_sort_order', table_name='credit_packages')
    op.drop_index('idx_credit_packages_is_active', table_name='credit_packages')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
