"""update_credit_transaction_for_event_sourcing

Revision ID: 743a8a8f6289
Revises: 5d14d51c20c3
Create Date: 2025-11-05 16:23:22.450678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743a8a8f6289'
down_revision: Union[str, None] = '5d14d51c20c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # CUSTOM: Migrate existing tenant credit balances to transaction log
    # This preserves existing balances as event-sourced transactions
    from sqlalchemy.sql import table, column
    from sqlalchemy import select, and_
    import uuid as uuid_lib
    from datetime import datetime

    # Create temporary table references for data migration
    tenants_temp = table('tenants',
        column('id', sa.UUID),
        column('credit_balance', sa.Integer),
    )

    credit_transactions_temp = table('credit_transactions',
        column('id', sa.UUID),
        column('tenant_id', sa.UUID),
        column('type', sa.String),
        column('amount', sa.Integer),
        column('balance_after', sa.Integer),
        column('description', sa.Text),
        column('transaction_metadata', sa.JSON),
        column('created_at', sa.DateTime),
    )

    # Get connection
    conn = op.get_bind()

    # Query tenants with existing balances
    result = conn.execute(
        select(tenants_temp.c.id, tenants_temp.c.credit_balance)
        .where(tenants_temp.c.credit_balance > 0)
    )

    # Create migration transactions for existing balances
    for tenant_id, balance in result:
        if balance > 0:
            conn.execute(
                credit_transactions_temp.insert().values(
                    id=uuid_lib.uuid4(),
                    tenant_id=tenant_id,
                    type='migration_balance_import',
                    amount=balance,
                    balance_after=balance,
                    description=f'Migrated existing credit balance: {balance} credits',
                    transaction_metadata={'source': 'tenant.credit_balance', 'migrated_at': datetime.utcnow().isoformat()},
                    created_at=datetime.utcnow(),
                )
            )

    # Now proceed with schema changes
    op.drop_index(op.f('idx_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_index(op.f('idx_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('idx_admin_audit_logs_resource'), table_name='admin_audit_logs')
    op.drop_index(op.f('idx_admin_audit_logs_user_id'), table_name='admin_audit_logs')
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_user_id'), 'admin_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_tenant_id'), 'api_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)

    # Add new columns as NULLABLE first to handle existing data
    op.add_column('credit_transactions', sa.Column('transaction_type', sa.String(length=50), nullable=True))
    op.add_column('credit_transactions', sa.Column('reference_type', sa.String(length=50), nullable=True))
    op.add_column('credit_transactions', sa.Column('reference_id', sa.UUID(), nullable=True))
    op.add_column('credit_transactions', sa.Column('stripe_charge_id', sa.String(length=255), nullable=True))
    op.add_column('credit_transactions', sa.Column('created_by_user_id', sa.UUID(), nullable=True))

    # Copy data from old columns to new columns for existing records
    conn.execute(sa.text('UPDATE credit_transactions SET transaction_type = type WHERE transaction_type IS NULL'))
    conn.execute(sa.text('UPDATE credit_transactions SET reference_type = related_type WHERE reference_type IS NULL'))
    conn.execute(sa.text('UPDATE credit_transactions SET reference_id = related_id WHERE reference_id IS NULL'))
    conn.execute(sa.text("UPDATE credit_transactions SET description = 'Legacy transaction' WHERE description IS NULL"))

    # Now make transaction_type and description NOT NULL
    op.alter_column('credit_transactions', 'transaction_type',
               existing_type=sa.String(length=50),
               nullable=False)
    op.alter_column('credit_transactions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('idx_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_index(op.f('idx_credit_transactions_tenant_id'), table_name='credit_transactions')
    op.drop_index(op.f('idx_credit_transactions_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_stripe_payment_intent_id'), table_name='credit_transactions')
    op.create_index(op.f('ix_credit_transactions_stripe_payment_intent_id'), 'credit_transactions', ['stripe_payment_intent_id'], unique=True)
    op.create_index('idx_credit_tx_reference', 'credit_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_credit_tx_stripe_intent', 'credit_transactions', ['stripe_payment_intent_id'], unique=False)
    op.create_index('idx_credit_tx_tenant_created', 'credit_transactions', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_credit_tx_type', 'credit_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_reference_id'), 'credit_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_transaction_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.create_foreign_key(None, 'credit_transactions', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('credit_transactions', 'related_id')
    op.drop_column('credit_transactions', 'related_type')
    op.drop_column('credit_transactions', 'balance_after')
    op.drop_column('credit_transactions', 'type')
    op.add_column('extraction_jobs', sa.Column('credits_cost', sa.Integer(), nullable=True))
    op.add_column('extraction_jobs', sa.Column('credits_deducted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('extraction_jobs', sa.Column('credit_transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'extraction_jobs', 'credit_transactions', ['credit_transaction_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tenants', 'credit_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('credit_balance', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'extraction_jobs', type_='foreignkey')
    op.drop_column('extraction_jobs', 'credit_transaction_id')
    op.drop_column('extraction_jobs', 'credits_deducted')
    op.drop_column('extraction_jobs', 'credits_cost')
    op.add_column('credit_transactions', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('credit_transactions', sa.Column('balance_after', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('credit_transactions', sa.Column('related_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('credit_transactions', sa.Column('related_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_credit_transactions_transaction_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_reference_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_index('idx_credit_tx_type', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_tenant_created', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_stripe_intent', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_reference', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_stripe_payment_intent_id'), table_name='credit_transactions')
    op.create_index(op.f('ix_credit_transactions_stripe_payment_intent_id'), 'credit_transactions', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('idx_credit_transactions_type'), 'credit_transactions', ['type'], unique=False)
    op.create_index(op.f('idx_credit_transactions_tenant_id'), 'credit_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.alter_column('credit_transactions', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('credit_transactions', 'created_by_user_id')
    op.drop_column('credit_transactions', 'stripe_charge_id')
    op.drop_column('credit_transactions', 'reference_id')
    op.drop_column('credit_transactions', 'reference_type')
    op.drop_column('credit_transactions', 'transaction_type')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_tenant_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_admin_audit_logs_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.create_index(op.f('idx_admin_audit_logs_user_id'), 'admin_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_admin_audit_logs_resource'), 'admin_audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('idx_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
