"""add_cached_balance_to_tenants

Revision ID: 34d31b85caab
Revises: 743a8a8f6289
Create Date: 2025-11-05 17:14:28.487497

FIX: Adds cached_balance column to tenants table for O(1) balance lookups.
Populates cached_balance from credit_transactions event log for existing tenants.
"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, select, func
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '34d31b85caab'
down_revision: Union[str, None] = '743a8a8f6289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns as nullable first
    op.add_column('tenants', sa.Column('cached_balance', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('balance_last_updated', sa.DateTime(), nullable=True))

    # Populate cached_balance from credit_transactions for existing tenants
    conn = op.get_bind()

    # Define table references for data migration
    tenants = table('tenants', column('id', UUID), column('cached_balance', sa.Integer), column('balance_last_updated', sa.DateTime))
    credit_transactions = table('credit_transactions', column('tenant_id', UUID), column('amount', sa.Integer))

    # Calculate balance for each tenant from transaction log
    balance_query = (
        select(
            credit_transactions.c.tenant_id,
            func.sum(credit_transactions.c.amount).label('total_balance')
        )
        .group_by(credit_transactions.c.tenant_id)
    )

    results = conn.execute(balance_query)
    now = datetime.utcnow()

    # Update each tenant's cached_balance
    for tenant_id, balance in results:
        conn.execute(
            tenants.update()
            .where(tenants.c.id == tenant_id)
            .values(
                cached_balance=max(0, balance if balance else 0),
                balance_last_updated=now
            )
        )

    # Set cached_balance to 0 for tenants with no transactions
    conn.execute(
        tenants.update()
        .where(tenants.c.cached_balance == None)
        .values(cached_balance=0, balance_last_updated=now)
    )

    # Now make cached_balance NOT NULL
    op.alter_column('tenants', 'cached_balance', nullable=False)

    # Create index
    op.create_index(op.f('ix_tenants_cached_balance'), 'tenants', ['cached_balance'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_cached_balance'), table_name='tenants')
    op.drop_column('tenants', 'balance_last_updated')
    op.drop_column('tenants', 'cached_balance')
    # ### end Alembic commands ###
