"""add_schema_definitions_table

Revision ID: 085e0bd93771
Revises: 230e72f5ab37
Create Date: 2025-11-02 22:42:32.260252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '085e0bd93771'
down_revision: Union[str, None] = '230e72f5ab37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_schema_definitions_created_at', 'schema_definitions', ['created_at'], unique=False)
    op.create_index('idx_schema_definitions_name', 'schema_definitions', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_schema_definitions_name', table_name='schema_definitions')
    op.drop_index('idx_schema_definitions_created_at', table_name='schema_definitions')
    op.drop_table('schema_definitions')
    # ### end Alembic commands ###
